apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: redmine
  name: redmine
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redmine
    spec:
      containers:
      - env:
        - name: REDMINE_DB_MYSQL
          value: db
        - name: REDMINE_DB_PASSWORD
          value: example
        image: redmine
        name: redmine
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
